#!/bin/sh
#
# DOCUMENTROOT is the only part you need to edit
DOCUMENTROOT=/var/www/html

# where various third party packages are installed
HERE=`pwd`/packages

# add to LD_LIBRARY_PATH before loading third party packages
LBRYPATH=$HERE/lib

# which python we are using
PYTHON=`which python`

mkdir -p $DOCUMENTROOT/secure $DOCUMENTROOT/unsecured

# Note that /secure must run .cgi scripts
# /secure is protected by shibboleth authentication
sedme() {
	rm -f $2
	sed \
		-e "s?SSPH_PYTHON_PATH?$HERE?g" \
		-e "s?PYTHON?$PYTHON?" \
		-e "s?LBRYPATH?$LBRYPATH?" \
		-e "s?MODULE?$3?" \
		< $1 > $2
	chmod +x $2
}

sedme ssph.cgi $DOCUMENTROOT/secure/ssph.cgi return_
sedme ssph.cgi $DOCUMENTROOT/unsecured/ssph_confirm.cgi confirm



