#!/bin/sh
#
# DOCUMENTROOT is the only part you need to edit
DOCUMENTROOT=/var/www/html

#
HERE=`pwd`
PYTHON=`which python`

mkdir -p $DOCUMENTROOT/secure 

# Note that /secure must run .cgi scripts
# /secure is protected by shibboleth authentication

sed -e "s?SSPH_PYTHON_PATH?$HERE?g" -e "s?PYTHON?$PYTHON?" < return.cgi  > $DOCUMENTROOT/secure/return.cgi

